// swift-tools-version:5.9
// This file is auto-generated by react-native-skia-binaries. Do not edit.
import PackageDescription

let package = Package(
    name: "react-native-skia-binaries",
    platforms: [
        .iOS(.v13)
    ],
    products: [
        .library(
            name: "SkiaBinaries",
            targets: [
                "libdawn_combined",
                "libskia",
                "libskottie",
                "libskparagraph",
                "libsksg",
                "libskshaper",
                "libskunicode_core",
                "libskunicode_libgrapheme",
                "libsvg",
            ]
        )
    ],
    targets: [
        .binaryTarget(
            name: "libdawn_combined",
            url: "https://github.com/wcandillon/react-native-skia-binaries/releases/download/154.0.0/libdawn_combined.xcframework.zip",
            checksum: "1246b53ed3ed9b0ffefb7c3a209f38c8f2f308665ae445410b07858f963090a6"
        ),
        .binaryTarget(
            name: "libskia",
            url: "https://github.com/wcandillon/react-native-skia-binaries/releases/download/154.0.0/libskia.xcframework.zip",
            checksum: "86affafa4d1b1814c18f712f3419eda6cedd79bb3cc6be95ebe891ce3e6aeca9"
        ),
        .binaryTarget(
            name: "libskottie",
            url: "https://github.com/wcandillon/react-native-skia-binaries/releases/download/154.0.0/libskottie.xcframework.zip",
            checksum: "ef0347644a7aa906d52cc2bcb063bf05d7a2dbe3cd06784242c7c2bcb3f39ef2"
        ),
        .binaryTarget(
            name: "libskparagraph",
            url: "https://github.com/wcandillon/react-native-skia-binaries/releases/download/154.0.0/libskparagraph.xcframework.zip",
            checksum: "8b7140b261045f18fbf6ca701574d2d8e0af82d053f791a58e6889bd82412ad9"
        ),
        .binaryTarget(
            name: "libsksg",
            url: "https://github.com/wcandillon/react-native-skia-binaries/releases/download/154.0.0/libsksg.xcframework.zip",
            checksum: "f640223e5613b9a0b23c4cfd24380eeb2ccca21c63a10891ec86d4c241e18a75"
        ),
        .binaryTarget(
            name: "libskshaper",
            url: "https://github.com/wcandillon/react-native-skia-binaries/releases/download/154.0.0/libskshaper.xcframework.zip",
            checksum: "a3bfef554b98f00d4490e330b1b2ba53e64f5cdc31235664620078c5b1bf85e6"
        ),
        .binaryTarget(
            name: "libskunicode_core",
            url: "https://github.com/wcandillon/react-native-skia-binaries/releases/download/154.0.0/libskunicode_core.xcframework.zip",
            checksum: "0270867d4c7a0bd00e366f20a1b6275928e4945a17ec674ab9aa5b5e337c5e14"
        ),
        .binaryTarget(
            name: "libskunicode_libgrapheme",
            url: "https://github.com/wcandillon/react-native-skia-binaries/releases/download/154.0.0/libskunicode_libgrapheme.xcframework.zip",
            checksum: "72f15efae0d8d933a1f3bc54936f27f1a79505bc315ef778ab70213ef51cdc45"
        ),
        .binaryTarget(
            name: "libsvg",
            url: "https://github.com/wcandillon/react-native-skia-binaries/releases/download/154.0.0/libsvg.xcframework.zip",
            checksum: "cebfb3976fd9345f91de77004798e2b08c9b664c910e04431c68dfa41427b729"
        ),
    ]
)
